apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-openapi-@color@
  labels:
    app: mp-openapi
spec:
  replicas: 3
  selector:
     matchLabels:
       app: mp-openapi
  template:
    metadata:
      labels:
        color: @color@
        app: mp-openapi
    spec:
      containers:
      - name: bgdemo
        image: icp.master:8500/mp-openapi:@image-tag@
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
